[package]
name = "examples"
version = "0.0.0"
publish = false
edition = "2021"

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
swiftide = { path = "../swiftide/" }
tracing-subscriber = "0.3"

[[example]]
name = "ingest-codebase"
path = "ingest_codebase.rs"
